### ISSUE TITLE
Excuses, what does `don't pop up font menu` means here???

### ISSUE THREAD

**Issue by touxstone** [anmonteiro/dotfiles#1]
Hi, 
I guess what a `font menu` could mean, & `popping` it `up` as well but even that, I cannot guess what's the function of the following code line [`ui.el/line66`](https://github.com/anmonteiro/dotfiles/blob/de3daeed3efe4ffd3285655cf384c962665802f4/.emacs.d/customizations/ui.el#L66)

**Comment by anmonteiro** [comment]
On macOS at least, there's a native font chooser menu that I don't want to be opened when clicking `s-t`

**Comment by touxstone** [comment]
Aha. OK (not my case, good!). Now I got it. I do appreciate your clarification.
